### ISSUE TITLE
Full Stage View icon's background is not transparent

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/dark-theme#21] opened 2020-05-28 14:28 UTC
IIRC it comes from a Pipeline Plugin

![image](https://user-images.githubusercontent.com/3000480/83154238-2d483400-a100-11ea-90b1-73c81311448c.png)

**Comment by timja** [comment] 2020-05-28 14:49
Duplicate of https://github.com/jenkinsci/dark-theme/issues/4

**Closed by timja** 2020-05-28 14:49 UTC
Labels: bug, plugin-compatibility

**Comment by oleg-nenashev** [comment] 2020-05-28 15:00
oops
